#!/usr/bin/env python3
"""Generate ignored ESP-IDF Kconfig defaults from a local .env file."""

from __future__ import annotations

import argparse
from pathlib import Path
import shlex


MAPPING = {
    "WIFI_SSID": "REMOTE_HID_WIFI_SSID",
    "WIFI_PASSWORD": "REMOTE_HID_WIFI_PASSWORD",
    "API_TOKEN": "REMOTE_HID_API_TOKEN",
    "KEY_HOLD_TIMEOUT_MS": "REMOTE_HID_KEY_HOLD_TIMEOUT_MS",
    "KEY_PRESS_DURATION_MS": "REMOTE_HID_KEY_PRESS_DURATION_MS",
}


def parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise ValueError(f"{path}:{line_number}: expected KEY=VALUE")
        name, raw_value = line.split("=", 1)
        name = name.strip()
        if name not in MAPPING:
            continue
        raw_value = raw_value.strip()
        if raw_value and raw_value[0] in "'\"":
            try:
                value = shlex.split(raw_value, comments=False, posix=True)[0]
            except (ValueError, IndexError) as exc:
                raise ValueError(f"{path}:{line_number}: invalid quoted value") from exc
        else:
            value = raw_value.split(" #", 1)[0].rstrip()
        values[name] = value
    return values


def kconfig_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def generate(values: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/generate_sdkconfig.py; do not commit this file.",
        "# Local credentials are intentionally kept in sdkconfig.defaults.local.",
    ]
    for env_name, kconfig_name in MAPPING.items():
        if env_name not in values:
            continue
        value = values[env_name]
        if env_name.endswith("_MS"):
            if not value.isdigit() or int(value) <= 0:
                raise ValueError(f"{env_name} must be a positive integer")
            lines.append(f"CONFIG_{kconfig_name}={value}")
        else:
            lines.append(f"CONFIG_{kconfig_name}={kconfig_string(value)}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--env-file", type=Path, default=Path(".env"))
    parser.add_argument("--output", type=Path, default=Path("sdkconfig.defaults.local"))
    args = parser.parse_args()
    if not args.env_file.exists():
        parser.error(f"environment file does not exist: {args.env_file}")
    try:
        output = generate(parse_env(args.env_file))
    except ValueError as exc:
        parser.error(str(exc))
    args.output.write_text(output, encoding="utf-8")
    print(f"Generated {args.output} from {args.env_file} (credentials not printed).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
